#!/bin/sh -xv

cd /mnt/reports/tables/supp_tables
cp prettifying1.csv tmp.csv

sed -i 's/[0-9]*,//' tmp.csv
sed -i 's/,/,/' tmp.csv
sed -i 's/feature_ugly/feature_pretty_/' tmp.csv
sed -i 's/Patient age/Age_/' tmp.csv
sed -i 's/Marital status/Marital status_/' tmp.csv
sed -i 's/Hypertension/Hypertension_/' tmp.csv
sed -i 's/Race/Race_/' tmp.csv
sed -i 's/Number morbidities/Number of morbidities_/' tmp.csv
sed -i 's/Ed 6month total/Number of ED visits in past 6 months_/' tmp.csv
sed -i 's/Primary diagnosis code/Primary diagnosis_/' tmp.csv
sed -i 's/Number past admissions/Number of past admissions_/' tmp.csv
sed -i 's/Admit source description/Admit source description_/' tmp.csv
sed -i 's/Acs blockgroup geoid/ACS BlockGroup GeoID_/' tmp.csv
sed -i 's/Dischargedispositiondescription/Discharge disposition description_/' tmp.csv
sed -i 's/Medsondischargedate/Medications administered in hospital on day of discharge_/' tmp.csv
sed -i 's/Acs population employed civilians/ACS Employed population count_/' tmp.csv
sed -i 's/Ed 6month/Has had at least 1 ED encounter in the past 6 months_/' tmp.csv
sed -i 's/Acs 200 and over ratio income poverty level past 12 mo/ACS Income over twice the poverty level_/' tmp.csv
sed -i 's/Acs married couple family/ACS Number of married couple families_/' tmp.csv
sed -i 's/Acs race white alone/"ACS Race, white alone"_/' tmp.csv
sed -i 's/Acs total population count/ACS Total population count_/' tmp.csv
sed -i 's/Days between current admission and previous discharge/Days between current admission and previous discharge_/' tmp.csv
sed -i 's/Acs 50 to 99 ratio income poverty level past 12 mo/ACS Income between 50 and 99 percent of poverty level_/' tmp.csv
sed -i 's/Gender/Gender_/' tmp.csv
sed -i 's/Bmi discharge/BMI on discharge_/' tmp.csv
sed -i 's/Bmi admit/BMI on admission_/' tmp.csv
sed -i 's/Depression/Depression_/' tmp.csv
sed -i 's/Acs under 50 ratio income poverty level past 12 mo/ACS Income below 50 percent of poverty level_/' tmp.csv
sed -i 's/Any cancer not skin/"Cancer, excluding skin cancers"_/' tmp.csv
sed -i 's/Rdw admit value/RDW value on admission_/' tmp.csv
sed -i 's/Acs race black alone/"ACS Race, black alone"_/' tmp.csv
sed -i 's/Length of stay in days/Length of stay in days_/' tmp.csv
sed -i 's/Discharge diastolic bp/Diastolic BP on discharge_/' tmp.csv
sed -i 's/Wbc admit value/WBC value on admission_/' tmp.csv
sed -i 's/B23025 003e/ACS Population employed_/' tmp.csv
sed -i 's/Admit diastolic bp/Diastolic BP on admission_/' tmp.csv
sed -i 's/Renal disease/Renal disease_/' tmp.csv
sed -i 's/Ed admission/Admitted from ED_/' tmp.csv
sed -i 's/Metastatic solid tumor/Metastatic solid tumor_/' tmp.csv
sed -i 's/Acs 125 to 149 ratio income poverty level past 12 mo/ACS Income between 125 and 149 percent of poverty level_/' tmp.csv
sed -i 's/Abs neut anc admit value/ANC value on admission_/' tmp.csv
sed -i 's/Cerebrovascular disease/Cerebrovascular disease_/' tmp.csv
sed -i 's/Acs 100 to 124 ratio income poverty level past 12 mo/ACS Income between 100 and 124 percent of poverty level_/' tmp.csv
sed -i 's/Congestive heart failure/Congestive heart failure_/' tmp.csv
sed -i 's/Admit systolic bp/Systolic BP on admission_/' tmp.csv
sed -i 's/Dischargemeds/Number of prescribed homegoing medications on day of discharge_/' tmp.csv
sed -i 's/Epilepsy/Epilepsy_/' tmp.csv
sed -i 's/Primary language/Primary language_/' tmp.csv
sed -i 's/Acs 150 to 184 ratio income poverty level past 12 mo/ACS Income between 150 and 184 percent of poverty level_/' tmp.csv
sed -i 's/Hemiplegia or paraplegia/Hemiplegia or paraplegia_/' tmp.csv
sed -i 's/Discharge systolic bp/Systolic BP on discharge_/' tmp.csv
sed -i 's/Mcv admit value/MCV value on admission_/' tmp.csv
sed -i 's/Rdw discharge value/RDW value on discharge_/' tmp.csv
sed -i 's/Neut admit value/Neutrophil value on admission_/' tmp.csv
sed -i 's/Rbc admit value/RBC value on admission_/' tmp.csv
sed -i 's/Wbc discharge value/WBC count on discharge_/' tmp.csv
sed -i 's/Anxiety/Anxiety_/' tmp.csv
sed -i 's/Admissiontime hospital burden/Number of other patients admitted on same day_/' tmp.csv
sed -i 's/Lymph admit value/Lymphocyte value on admission_/' tmp.csv
sed -i 's/Dischargedonopiate/Discharged with opiate prescription_/' tmp.csv
sed -i 's/Abs neut anc discharge value/ANC value on discharge_/' tmp.csv
sed -i 's/Length of stay of last admission/Length of stay of last admission_/' tmp.csv
sed -i 's/Acs female householder no husband present/"ACS Number of families with female householder, no husband present"_/' tmp.csv
sed -i 's/Ondialysis/On dialysis_/' tmp.csv
sed -i 's/Medsonadmitdate/Medications administered in hospital on day of admission_/' tmp.csv
sed -i 's/Hospital transfer description/Hospital transfer description_/' tmp.csv
sed -i 's/Temperature discharge/Temperature on discharge_/' tmp.csv
sed -i 's/Platelet count admit value/Platelet count on admission_/' tmp.csv
sed -i 's/Egfr aa discharge value/"EGFR adjusted for African Americans, discharge value"_/' tmp.csv
sed -i 's/Tpn/Received TPN_/' tmp.csv
sed -i 's/Hematocrit admit value/Hematocrit value on admission_/' tmp.csv
sed -i 's/Dischargetime hour of day/Discharge hour of day_/' tmp.csv
sed -i 's/B01002 001e/ACS Median age_/' tmp.csv
sed -i 's/B11001 009e/ACS Number of householders not living alone_/' tmp.csv
sed -i 's/B25010 001e/"ACS Average size of households, renters and owners"_/' tmp.csv
sed -i 's/Mcv discharge value/MCV value on discharge_/' tmp.csv
sed -i 's/B02001 008e/ACS Population identifying as two or more races_/' tmp.csv
sed -i 's/Dementia/Dementia_/' tmp.csv
sed -i 's/Abs lymph admit value/Absolute lymphocyte count on admission_/' tmp.csv
sed -i 's/B11001 005e/"ACS Number of families with male householder, no wife present"_/' tmp.csv
sed -i 's/Creatinine discharge value/Creatinine value on discharge_/' tmp.csv
sed -i 's/Egfr aa admit value/EGFR adjusted for African Americans, admit value_/' tmp.csv
sed -i 's/Neut discharge value/Neutrophil count at discharge_/' tmp.csv
sed -i 's/Rbc discharge value/RBC value at discharge_/' tmp.csv
sed -i 's/Lymph discharge value/Lymphocyte count at discharge_/' tmp.csv
sed -i 's/Medsfirst24hours/Medications administered in the first 24 hours_/' tmp.csv
sed -i 's/Platelet count discharge value/Platelet count at discharge_/' tmp.csv
sed -i 's/Creatinine admit value/Creatinine value on admission_/' tmp.csv
sed -i 's/B01002 002e/ACS Median age of males_/' tmp.csv
sed -i 's/Dischargetime weekofyear/Numeric week of year at discharge_/' tmp.csv
sed -i 's/Length of stay over 3 days/Length of stay over 3 days_/' tmp.csv
sed -i 's/Diabetes without chronic complication/Diabetes without chronic complication_/' tmp.csv
sed -i 's/Peripheral vascular disease/Peripheral vascular disease_/' tmp.csv
sed -i 's/Hematocrit discharge value/Hematocrit discharge value_/' tmp.csv
sed -i 's/B23025 005e/ACS Population unemployed_/' tmp.csv
sed -i 's/Cbc admit time hospital burden/Number of patients having CBCs drawn at this time, admission_/' tmp.csv
sed -i 's/Heartrate discharge/Heart rate on discharge_/' tmp.csv
sed -i 's/Dischargedonbenzo/Discharged on benzodiazepine_/' tmp.csv
sed -i 's/Mch admit value/MCH value on admission_/' tmp.csv
sed -i 's/B23025 007e/B23025 007e_/' tmp.csv
sed -i 's/Abs lymph discharge value/Absolute lymphocyte count at discharge_/' tmp.csv
sed -i 's/Benzosduringadmit/Benzodiazepines administered during admission_/' tmp.csv
sed -i 's/Cbc discharge time hospital burden/Number of patients having CBCs drawn at this time, discharge_/' tmp.csv
sed -i 's/Egfr other admit value/EGFR adjusted for other races, admit value_/' tmp.csv
sed -i 's/Temperature admit/Temperature on admission_/' tmp.csv
sed -i 's/Acs 185 to 199 ratio income poverty level past 12 mo/ACS Income between 185 and 199 percent of the poverty ratio_/' tmp.csv
sed -i 's/Pt ot consult/Patient received a consult from physical or occupational therapy_/' tmp.csv
sed -i 's/Chronic pulmonary disease/Chronic pulmonary disease_/' tmp.csv
sed -i 's/Heartrate admit/Heart rate on admission_/' tmp.csv
sed -i 's/Mchc discharge value/MCHC value on discharge_/' tmp.csv
sed -i 's/Opiatesduringadmit/Opiates received during admission_/' tmp.csv
sed -i 's/B01002 003e/ACS Median age of females_/' tmp.csv
sed -i 's/Hemoglobin discharge value/Hemoglobin value at discharge_/' tmp.csv
sed -i 's/Admissiontime weekofyear/Numeric week of the year on admission_/' tmp.csv
sed -i 's/B11001 008e/ACS Number of householders living alone_/' tmp.csv
sed -i 's/Pressureulcer no/Pressure ulcer absent_/' tmp.csv
sed -i 's/Psychosis/Psychosis_/' tmp.csv
sed -i 's/Dischargetime hospital burden/Number of other patients discharged on same day_/' tmp.csv
sed -i 's/Egfr other discharge value/EGFR adjusted for other race, discharge value_/' tmp.csv
sed -i 's/Geoprob new addr/Listed address is likely a new address_/' tmp.csv
sed -i 's/Mch discharge value/MCH value at discharge_/' tmp.csv
sed -i 's/Glucose discharge value/Glucose value at discharge_/' tmp.csv
sed -i 's/Length of stay over 5 days/Length of stay over 5 days_/' tmp.csv
sed -i 's/Bun discharge value/BUN value at discharge_/' tmp.csv
sed -i 's/Cmp discharge time hospital burden/Number of patients having CMPs drawn at this time, discharge_/' tmp.csv
sed -i 's/Icu length of stay in days/ICU length of stay in days_/' tmp.csv
sed -i 's/Glucose admit value/Glucose value on admission_/' tmp.csv
sed -i 's/Alkaline phosphatase admit value/Alkaline phosphatase value on admission_/' tmp.csv
sed -i 's/Alkaline phosphatase discharge value/Alkaline phosphatase value at discharge _/' tmp.csv
sed -i 's/Hemoglobin admit value/Hemoglobin value on admission_/' tmp.csv
sed -i 's/Baso discharge value/Basophil count at discharge_/' tmp.csv
sed -i 's/Cbc admit time on weekend/First CBC drawn on weekend_/' tmp.csv
sed -i 's/Cbc discharge time day of week/Weekday of last CBC result_/' tmp.csv
sed -i 's/Cbc discharge time at night 6p 10p/Last CBC resulted between 6 and 10pm_/' tmp.csv
sed -i 's/Cbc admit time weekofyear/Numeric week of year when first CBC resulted_/' tmp.csv
sed -i 's/Cbc admit time very late night 12a 4a/First CBC resulted between 12 and 4am_/' tmp.csv
sed -i 's/Cbc admit time quarter/Numeric quarter of the year when first CBC resulted_/' tmp.csv
sed -i 's/Cbc admit time on holiday/First CBC resulted on a US holiday_/' tmp.csv
sed -i 's/Cbc discharge time during working day 7a 6p/Last CBC resulted between 7am and 6pm_/' tmp.csv
sed -i 's/Cbc admit time month/Month of the year when first CBC resulted_/' tmp.csv
sed -i 's/Cbc admit time late night 10p 12a/Last CBC resulted between 10pm and 12am_/' tmp.csv
sed -i 's/Cbc admit time hour of day/Numeric hour of day when first CBC resulted_/' tmp.csv
sed -i 's/Abs mono admit value/Absolute monocyte count on admission_/' tmp.csv
sed -i 's/Abs mono discharge value/Absolute monocyte count at discharge_/' tmp.csv
sed -i 's/Abs eosin discharge value/Absolute eosinophil count at discharge_/' tmp.csv
sed -i 's/Abs eosin admit value/Absolute eosinophil count on admission_/' tmp.csv
sed -i 's/Cbc discharge time early morning 4a 7a/Last CBC resulted between 4 and 7am_/' tmp.csv
sed -i 's/Absolute nrbc discharge value/Absolute nrbc discharge value_/' tmp.csv
sed -i 's/Cbc discharge time hour of day/Cbc discharge time hour of day_/' tmp.csv
sed -i 's/Cbc discharge time late night 10p 12a/Cbc discharge time late night 10p 12a_/' tmp.csv
sed -i 's/Cbc discharge time month/Cbc discharge time month_/' tmp.csv
sed -i 's/Cbc discharge time on holiday/Cbc discharge time on holiday_/' tmp.csv
sed -i 's/Cbc discharge time on weekend/Cbc discharge time on weekend_/' tmp.csv
sed -i 's/Cbc discharge time quarter/Cbc discharge time quarter_/' tmp.csv
sed -i 's/Cbc discharge time very late night 12a 4a/Cbc discharge time very late night 12a 4a_/' tmp.csv
sed -i 's/Cbc discharge time weekofyear/Cbc discharge time weekofyear_/' tmp.csv
sed -i 's/Cdiffinfection/Cdiffinfection_/' tmp.csv
sed -i 's/Cerebral palsy/Cerebral palsy_/' tmp.csv
sed -i 's/Abs baso discharge value/Abs baso discharge value_/' tmp.csv
sed -i 's/Chloride admit value/Chloride admit value_/' tmp.csv
sed -i 's/Absolute nrbc admit value/Absolute nrbc admit value_/' tmp.csv
sed -i 's/Admissiontime at night 6p 10p/Admissiontime at night 6p 10p_/' tmp.csv
sed -i 's/Baso admit value/Baso admit value_/' tmp.csv
sed -i 's/Admissiontime day of week/Admission day of week_/' tmp.csv
sed -i 's/Ast discharge value/Ast discharge value_/' tmp.csv
sed -i 's/Ast admit value/Ast admit value_/' tmp.csv
sed -i 's/Anion gap discharge value/Anion gap discharge value_/' tmp.csv
sed -i 's/Anion gap admit value/Anion gap admit value_/' tmp.csv
sed -i 's/Alt discharge value/Alt discharge value_/' tmp.csv
sed -i 's/Bilirubin total admit value/Bilirubin total admit value_/' tmp.csv
sed -i 's/Bilirubin total discharge value/Bilirubin total discharge value_/' tmp.csv
sed -i 's/Alt admit value/Alt admit value_/' tmp.csv
sed -i 's/Albumin discharge value/Albumin discharge value_/' tmp.csv
sed -i 's/Albumin admit value/Albumin admit value_/' tmp.csv
sed -i 's/Aids hiv/Aids hiv_/' tmp.csv
sed -i 's/Bun admit value/BUN value on admission_/' tmp.csv
sed -i 's/Admissiontime very late night 12a 4a/Admissiontime very late night 12a 4a_/' tmp.csv
sed -i 's/Calcium admit value/Calcium admit value_/' tmp.csv
sed -i 's/Calcium discharge value/Calcium discharge value_/' tmp.csv
sed -i 's/Admissiontime quarter/Admissiontime quarter_/' tmp.csv
sed -i 's/Admissiontime on weekend/Admissiontime on weekend_/' tmp.csv
sed -i 's/Admissiontime on holiday/Admissiontime on holiday_/' tmp.csv
sed -i 's/Admissiontime month/Admissiontime month_/' tmp.csv
sed -i 's/Cbc admit time at night 6p 10p/Cbc admit time at night 6p 10p_/' tmp.csv
sed -i 's/Admissiontime late night 10p 12a/Admissiontime late night 10p 12a_/' tmp.csv
sed -i 's/Admissiontime hour of day/Admissiontime hour of day_/' tmp.csv
sed -i 's/Cbc admit time day of week/First CBC resulted day of week_/' tmp.csv
sed -i 's/Cbc admit time during working day 7a 6p/Cbc admit time during working day 7a 6p_/' tmp.csv
sed -i 's/Admissiontime early morning 4a 7a/Admissiontime early morning 4a 7a_/' tmp.csv
sed -i 's/Cbc admit time early morning 4a 7a/Cbc admit time early morning 4a 7a_/' tmp.csv
sed -i 's/Admissiontime during working day 7a 6p/Admitted between 7am and 6pm_/' tmp.csv
sed -i 's/Chloride discharge value/Chloride discharge value_/' tmp.csv
sed -i 's/Dischargetime late night 10p 12a/Dischargetime late night 10p 12a_/' tmp.csv
sed -i 's/Cmp admit time at night 6p 10p/Cmp admit time at night 6p 10p_/' tmp.csv
sed -i 's/Mchc admit value/Mchc admit value_/' tmp.csv
sed -i 's/Nucleated reds admit value/Nucleated reds admit value_/' tmp.csv
sed -i 's/Myocardial infarction/Myocardial infarction_/' tmp.csv
sed -i 's/Mpv discharge value/Mpv discharge value_/' tmp.csv
sed -i 's/Mpv admit value/Mpv admit value_/' tmp.csv
sed -i 's/Mono discharge value/Mono discharge value_/' tmp.csv
sed -i 's/Mono admit value/Mono admit value_/' tmp.csv
sed -i 's/Moderate or severe liver disease/Moderate or severe liver disease_/' tmp.csv
sed -i 's/Mild liver disease/Mild liver disease_/' tmp.csv
sed -i 's/Lineinfection/Lineinfection_/' tmp.csv
sed -i 's/Cmp admit time day of week/First CMP resulted day of week_/' tmp.csv
sed -i 's/Length of stay over 7 days/Length of stay over 7 days_/' tmp.csv
sed -i 's/Length of stay over 14 days/Length of stay over 14 days_/' tmp.csv
sed -i 's/Knee replacement/Knee replacement_/' tmp.csv
sed -i 's/Infectiousdiseaseconsult/Infectiousdiseaseconsult_/' tmp.csv
sed -i 's/In this admission lasticudischarge/Discharged from ICU at any point during current hospitalization_/' tmp.csv
sed -i 's/In this admission firsticuadmit/Admitted to ICU at any point during current hospitalization_/' tmp.csv
sed -i 's/Hospiceconsult/Hospice consult received_/' tmp.csv
sed -i 's/Hip replacement/Hip replacement_/' tmp.csv
sed -i 's/Nucleated reds discharge value/Nucleated reds discharge value_/' tmp.csv
sed -i 's/On day of admission firsticuadmit/Admitted to ICU on first day of hospitalization_/' tmp.csv
sed -i 's/On day of admission lasticudischarge/Discharged from ICU on first day of hospitalization_/' tmp.csv
sed -i 's/Palliativecareconsult/Palliativecareconsult_/' tmp.csv
sed -i 's/Spiritualcareconsult/Spiritualcareconsult_/' tmp.csv
sed -i 's/Solid organ transplant/Solid organ transplant_/' tmp.csv
sed -i 's/Sodium discharge value/Sodium discharge value_/' tmp.csv
sed -i 's/Sodium admit value/Sodium admit value_/' tmp.csv
sed -i 's/Short gut syndrome/Short gut syndrome_/' tmp.csv
sed -i 's/Rheumatic disease/Rheumatic disease_/' tmp.csv
sed -i 's/Protein total discharge value/Protein total discharge value_/' tmp.csv
sed -i 's/Protein total admit value/Protein total admit value_/' tmp.csv
sed -i 's/Pressureulcer nan/Pressure ulcer information unavailable_/' tmp.csv
sed -i 's/Pressureulcer yes/Pressure ulcer_/' tmp.csv
sed -i 's/Pressureulcer present on admission to the hospital/Pressure ulcer present on admission to the hospital_/' tmp.csv
sed -i 's/Pressureulcer history of pressure ulcer/History of pressure ulcer_/' tmp.csv
sed -i 's/Potassium discharge value/Potassium discharge value_/' tmp.csv
sed -i 's/Potassium admit value/Potassium admit value_/' tmp.csv
sed -i 's/Pneumonia/Pneumonia_/' tmp.csv
sed -i 's/Peptic ulcer disease/Peptic ulcer disease_/' tmp.csv
sed -i 's/Patientclassdescription/Patient class description_/' tmp.csv
sed -i 's/Fallduringadmission/Fallduringadmission_/' tmp.csv
sed -i 's/Eosin discharge value/Eosin discharge value_/' tmp.csv
sed -i 's/Eosin admit value/Eosin admit value_/' tmp.csv
sed -i 's/Cmp discharge time on holiday/Cmp discharge time on holiday_/' tmp.csv
sed -i 's/Cmp discharge time late night 10p 12a/Cmp discharge time late night 10p 12a_/' tmp.csv
sed -i 's/Cmp discharge time hour of day/Cmp discharge time hour of day_/' tmp.csv
sed -i 's/Cmp discharge time early morning 4a 7a/Cmp discharge time early morning 4a 7a_/' tmp.csv
sed -i 's/Cmp discharge time during working day 7a 6p/Cmp discharge time during working day 7a 6p_/' tmp.csv
sed -i 's/Cmp discharge time day of week/Cmp discharge time day of week_/' tmp.csv
sed -i 's/Cmp discharge time at night 6p 10p/Cmp discharge time at night 6p 10p_/' tmp.csv
sed -i 's/Cmp admit time weekofyear/Cmp admit time weekofyear_/' tmp.csv
sed -i 's/Cmp admit time very late night 12a 4a/Cmp admit time very late night 12a 4a_/' tmp.csv
sed -i 's/Cmp admit time quarter/Cmp admit time quarter_/' tmp.csv
sed -i 's/Cmp admit time on weekend/Cmp admit time on weekend_/' tmp.csv
sed -i 's/Cmp admit time on holiday/Cmp admit time on holiday_/' tmp.csv
sed -i 's/Cmp admit time month/Cmp admit time month_/' tmp.csv
sed -i 's/Cmp admit time late night 10p 12a/Cmp admit time late night 10p 12a_/' tmp.csv
sed -i 's/Cmp admit time hour of day/Cmp admit time hour of day_/' tmp.csv
sed -i 's/Cmp admit time hospital burden/Cmp admit time hospital burden_/' tmp.csv
sed -i 's/Cmp admit time early morning 4a 7a/Cmp admit time early morning 4a 7a_/' tmp.csv
sed -i 's/Cmp admit time during working day 7a 6p/Cmp admit time during working day 7a 6p_/' tmp.csv
sed -i 's/Cmp discharge time month/Cmp discharge time month_/' tmp.csv
sed -i 's/Cmp discharge time on weekend/Cmp discharge time on weekend_/' tmp.csv
sed -i 's/Dischargetime very late night 12a 4a/Dischargetime very late night 12a 4a_/' tmp.csv
sed -i 's/Cmp discharge time quarter/Cmp discharge time quarter_/' tmp.csv
sed -i 's/Dischargetime quarter/Dischargetime quarter_/' tmp.csv
sed -i 's/Dischargetime on weekend/Dischargetime on weekend_/' tmp.csv
sed -i 's/Dischargetime on holiday/Dischargetime on holiday_/' tmp.csv
sed -i 's/Dischargetime month/Dischargetime month_/' tmp.csv
sed -i 's/Dischargetime early morning 4a 7a/Dischargetime early morning 4a 7a_/' tmp.csv
sed -i 's/Dischargetime during working day 7a 6p/Dischargetime during working day 7a 6p_/' tmp.csv
sed -i 's/Dischargetime day of week/Dischargetime day of week_/' tmp.csv
sed -i 's/Dischargetime at night 6p 10p/Dischargetime at night 6p 10p_/' tmp.csv
sed -i 's/Discharged in past 30d/Had a hospital discharge in the past 30 days_/' tmp.csv
sed -i 's/Diff type discharge value/Diff type discharge value_/' tmp.csv
sed -i 's/Diff type admit value/Diff type admit value_/' tmp.csv
sed -i 's/Diabetes with chronic complication/Diabetes with chronic complication_/' tmp.csv
sed -i 's/Connective tissue disorder/Connective tissue disorder_/' tmp.csv
sed -i 's/Co2 discharge value/Co2 discharge value_/' tmp.csv
sed -i 's/Co2 admit value/Co2 admit value_/' tmp.csv
sed -i 's/Cmp discharge time weekofyear/Cmp discharge time weekofyear_/' tmp.csv
sed -i 's/Cmp discharge time very late night 12a 4a/Cmp discharge time very late night 12a 4a_/' tmp.csv
sed -i 's/Abs baso admit value/Abs baso admit value_/' tmp.csv
sed -i 's/Insurance2/Insurance provider_/' tmp.csv
sed -i 's/Financialclass nan/Financial class information unavailable_/' tmp.csv
sed -i 's/Readmitted90d/Readmitted within 90 days_/' tmp.csv
sed -i 's/Financialclass medicare/Medicare_/' tmp.csv
sed -i 's/Readmitted365d/Readmitted within 365 days_/' tmp.csv
sed -i 's/Readmitted1d/Readmitted within 1 day_/' tmp.csv
sed -i 's/Readmitted28d/Readmitted within 28 days_/' tmp.csv
sed -i 's/Readmitted20d/Readmitted within 20 days_/' tmp.csv
sed -i 's/Readmitted30d/Readmitted within 30 days_/' tmp.csv
sed -i 's/Readmitted3650d/Readmitted within 3650 days_/' tmp.csv
sed -i 's/Readmitted3d/Readmitted within 3 days_/' tmp.csv
sed -i 's/Readmitted45d/Readmitted within 45 days_/' tmp.csv
sed -i 's/Readmitted5d/Readmitted within 5 days_/' tmp.csv
sed -i 's/Readmitted7d/Readmitted within 7 days_/' tmp.csv
sed -i 's/Readmitted15d/Readmitted within 15 days_/' tmp.csv
sed -i 's/Readmitted180d/Readmitted within 180 days_/' tmp.csv
sed -i 's/Financialclass private health insurance/Private health insurance_/' tmp.csv
sed -i 's/Financialclass other/Insurance other_/' tmp.csv
sed -i 's/Financialclass medicaid/Medicaid_/' tmp.csv
sed -i 's/Readmitted0 5d/Readmitted within 12 Hours_/' tmp.csv
sed -i 's/cmp_admit_time_within_24h/CMP resulted within 24 hours of admission_/' tmp.csv
sed -i 's/cbc_admit_time_within_24h/CBC resulted within 24 hours of admission_/' tmp.csv
sed -i 's/Attending specialty institute desc/Department of attending physician_/' tmp.csv
sed -i 's/_,.*//' tmp.csv
sed -i 's/_//' tmp.csv
sed -i 's/"//g' tmp.csv
# rm tmp.csv
